import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from '@/components/shared/sidebar/sidebar'
import { ThemeProvider } from '@/components/theme-provider'
import { ThemeSwitcher } from '@/components/shared/theme-switcher'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className}`}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <main className='flex h-screen w-screen'>
            <div>
              <div className='absolute right-5 top-5'>
                <ThemeSwitcher />
              </div>
              <div className=''>
                <Sidebar />
              </div>
            </div>
            <div className='h-full w-full p-5'>{children}</div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
